const countries = [
  { name: "Afghanistan", abrv: "AFG" },
  { name: "Albania", abrv: "ALB" },
  { name: "Algeria", abrv: "DZA" },
  { name: "Andorra", abrv: "AND" },
  { name: "Angola", abrv: "AGO" },
  { name: "Antigua and Barbuda", abrv: "ATG" },
  { name: "Argentina", abrv: "ARG" },
  { name: "Armenia", abrv: "ARM" },
  { name: "Australia", abrv: "AUS" },
  { name: "Austria", abrv: "AUT" },
  { name: "Azerbaijan", abrv: "AZE" },
  { name: "Bahamas", abrv: "BHS" },
  { name: "Bahrain", abrv: "BHR" },
  { name: "Bangladesh", abrv: "BGD" },
  { name: "Barbados", abrv: "BRB" },
  { name: "Belarus", abrv: "BLR" },
  { name: "Belgium", abrv: "BEL" },
  { name: "Belize", abrv: "BLZ" },
  { name: "Benin", abrv: "BEN" },
  { name: "Bhutan", abrv: "BTN" },
  { name: "Bolivia", abrv: "BOL" },
  { name: "Bosnia and Herzegovina", abrv: "BIH" },
  { name: "Botswana", abrv: "BWA" },
  { name: "Brazil", abrv: "BRA" },
  { name: "Brunei", abrv: "BRN" },
  { name: "Bulgaria", abrv: "BGR" },
  { name: "Burkina Faso", abrv: "BFA" },
  { name: "Burundi", abrv: "BDI" },
  { name: "Cabo Verde", abrv: "CPV" },
  { name: "Cambodia", abrv: "KHM" },
  { name: "Cameroon", abrv: "CMR" },
  { name: "Canada", abrv: "CAN" },
  { name: "Central African Republic", abrv: "CAF" },
  { name: "Chad", abrv: "TCD" },
  { name: "Chile", abrv: "CHL" },
  { name: "China", abrv: "CHN" },
  { name: "Colombia", abrv: "COL" },
  { name: "Comoros", abrv: "COM" },
  { name: "Congo", abrv: "COG" },
  { name: "Democratic Republic of the Congo", abrv: "COD" },
  { name: "Costa Rica", abrv: "CRI" },
  { name: "Croatia", abrv: "HRV" },
  { name: "Cuba", abrv: "CUB" },
  { name: "Cyprus", abrv: "CYP" },
  { name: "Czechia", abrv: "CZE" },
  { name: "Denmark", abrv: "DNK" },
  { name: "Djibouti", abrv: "DJI" },
  { name: "Dominica", abrv: "DMA" },
  { name: "Dominican Republic", abrv: "DOM" },
  { name: "Ecuador", abrv: "ECU" },
  { name: "Egypt", abrv: "EGY" },
  { name: "El Salvador", abrv: "SLV" },
  { name: "Equatorial Guinea", abrv: "GNQ" },
  { name: "Eritrea", abrv: "ERI" },
  { name: "Estonia", abrv: "EST" },
  { name: "Eswatini", abrv: "SWZ" },
  { name: "Ethiopia", abrv: "ETH" },
  { name: "Fiji", abrv: "FJI" },
  { name: "Finland", abrv: "FIN" },
  { name: "France", abrv: "FRA" },
  { name: "Gabon", abrv: "GAB" },
  { name: "Gambia", abrv: "GMB" },
  { name: "Georgia", abrv: "GEO" },
  { name: "Germany", abrv: "DEU" },
  { name: "Ghana", abrv: "GHA" },
  { name: "Greece", abrv: "GRC" },
  { name: "Grenada", abrv: "GRD" },
  { name: "Guatemala", abrv: "GTM" },
  { name: "Guinea", abrv: "GIN" },
  { name: "Guinea-Bissau", abrv: "GNB" },
  { name: "Guyana", abrv: "GUY" },
  { name: "Haiti", abrv: "HTI" },
  { name: "Honduras", abrv: "HND" },
  { name: "Hungary", abrv: "HUN" },
  { name: "Iceland", abrv: "ISL" },
  { name: "India", abrv: "IND" },
  { name: "Indonesia", abrv: "IDN" },
  { name: "Iran", abrv: "IRN" },
  { name: "Iraq", abrv: "IRQ" },
  { name: "Ireland", abrv: "IRL" },
  { name: "Israel", abrv: "ISR" },
  { name: "Italy", abrv: "ITA" },
  { name: "Jamaica", abrv: "JAM" },
  { name: "Japan", abrv: "JPN" },
  { name: "Jordan", abrv: "JOR" },
  { name: "Kazakhstan", abrv: "KAZ" },
  { name: "Kenya", abrv: "KEN" },
  { name: "South Korea", abrv: "KOR" },
  { name: "North Korea", abrv: "PRK" },
  { name: "Kuwait", abrv: "KWT" },
  { name: "Kyrgyzstan", abrv: "KGZ" },
  { name: "Laos", abrv: "LAO" },
  { name: "Latvia", abrv: "LVA" },
  { name: "Lebanon", abrv: "LBN" },
  { name: "Libya", abrv: "LBY" },
  { name: "Luxembourg", abrv: "LUX" },
  { name: "Malaysia", abrv: "MYS" },
  { name: "Mexico", abrv: "MEX" },
  { name: "Netherlands", abrv: "NLD" },
  { name: "New Zealand", abrv: "NZL" },
  { name: "United Kingdom", abrv: "GBR" },
  { name: "United States", abrv: "USA" },
  { name: "Vietnam", abrv: "VNM" }
];

export default countries;